# Generated by Django 2.0.1 on 2018-01-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_timestamp', models.IntegerField()),
                ('pm1', models.DecimalField(decimal_places=7, max_digits=15)),
                ('pm2_5', models.DecimalField(decimal_places=7, max_digits=15)),
                ('pm10', models.DecimalField(decimal_places=7, max_digits=15)),
                ('temperature', models.DecimalField(decimal_places=7, max_digits=15)),
                ('humidity', models.DecimalField(decimal_places=7, max_digits=15)),
                ('bin0', models.IntegerField()),
                ('bin1', models.IntegerField()),
                ('bin2', models.IntegerField()),
                ('bin3', models.IntegerField()),
                ('bin4', models.IntegerField()),
                ('bin5', models.IntegerField()),
                ('bin6', models.IntegerField()),
                ('bin7', models.IntegerField()),
                ('bin8', models.IntegerField()),
                ('bin9', models.IntegerField()),
                ('bin10', models.IntegerField()),
                ('bin11', models.IntegerField()),
                ('bin12', models.IntegerField()),
                ('bin13', models.IntegerField()),
                ('bin14', models.IntegerField()),
                ('bin15', models.IntegerField()),
                ('total', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=15)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=15)),
                ('altitude', models.DecimalField(decimal_places=7, max_digits=15)),
                ('accuracy', models.DecimalField(decimal_places=7, max_digits=15)),
                ('time', models.CharField(max_length=50)),
            ],
        ),
    ]
