# Generated by Django 2.0.1 on 2018-01-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_mihai', '0002_auto_20180129_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collecteddata',
            name='phone_timestamp',
            field=models.BigIntegerField(),
        ),
    ]
