# Generated by Django 2.0.1 on 2018-02-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_mihai', '0006_auto_20180227_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collecteddata',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
